#!/usr/bin/env bash
# deepseek-v4-flash-nvfp4 — vLLM stacked (multi-node) controller
# Model:    nvidia/DeepSeek-V4-Flash-NVFP4 @ e3cd60e7de98e9867116860d522499a728de1cf9
# Target:   dgx-spark-stacked | Generated by LMDS 0.1.0 (rule-based)
# Topology: stacked — 2 nodes, tensor-parallel 2, mp backend (worker-first startup)
# Standard: dgx-spark-controllers v3.0.0 controller contract + validated stacked reference (v8.2)
#
# หลักการ (จาก skills_Strack.md):
#   - worker-first: เปิด rank 1 (headless) ก่อน แล้วค่อยเปิด rank 0 (API)
#   - lock runtime image ด้วย image-ID ให้ตรงกันทั้งสอง node ก่อน start
#   - แยก lifecycle: prepare-runtime → download → verify-files → sync-worker → verify-worker → start
#   - ต้องมี fabric ระหว่าง node (200G RoCE/Ethernet) + passwordless SSH master→worker
set -Eeuo pipefail

# ============================ CONFIG (แก้ได้ผ่าน env) ============================
SLUG="deepseek-v4-flash-nvfp4"
SCRIPT_VERSION="${SCRIPT_VERSION:-0.1.0}"
MODEL_LABEL="${MODEL_LABEL:-nvidia/DeepSeek-V4-Flash-NVFP4}"
RUNTIME_LABEL="${RUNTIME_LABEL:-vLLM (Docker)}"
MODEL_FEATURES="${MODEL_FEATURES:-text}"
MODEL_ID="nvidia/DeepSeek-V4-Flash-NVFP4"
MODEL_REVISION="e3cd60e7de98e9867116860d522499a728de1cf9"
SERVED_MODEL_NAME="deepseek-v4-flash-nvfp4"
VLLM_IMAGE="${VLLM_IMAGE:-ghcr.io/anemll/dspark-vllm-gx10:0.1.1}"
MASTER_CONTAINER="${MASTER_CONTAINER:-lmds-deepseek-v4-flash-nvfp4-head}"
WORKER_CONTAINER="${WORKER_CONTAINER:-lmds-deepseek-v4-flash-nvfp4-worker}"

# ── Cluster nodes (ต้องแก้ให้ตรงเครื่องจริง) ──
# hub เขียน cluster.env ให้ได้ด้วย `lmds node cluster --write deepseek-v4-flash-nvfp4` — มีก็ใช้เลยไม่ต้องถาม
# env ที่ตั้งมาจากภายนอกยังชนะไฟล์นี้เสมอ (ไฟล์ถูกอ่านก่อน default ทั้งหมดด้านล่าง)
CLUSTER_ENV="${CLUSTER_ENV:-$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/cluster.env}"
if [[ -f "$CLUSTER_ENV" ]]; then
  set -a; . "$CLUSTER_ENV"; set +a
fi

MASTER_IP="${MASTER_IP:-10.100.152.1}"
WORKER_IP="${WORKER_IP:-10.100.152.2}"
SSH_USER="${SSH_USER:-${USER:-$(id -un)}}"
# คลัสเตอร์ที่มากกว่า 2 เครื่อง: ใส่ IP ของ worker ทุกตัวคั่นด้วยช่องว่าง เรียงตาม node-rank
# (rank 1, 2, 3 …) · ค่าเริ่มต้นคือ worker เดียว = พฤติกรรมเดิมทุกประการ
WORKER_IPS="${WORKER_IPS:-$WORKER_IP}"
# fabric/transport IP สำหรับ NCCL — ถ้าใช้ QSFP แยก interface ให้ override สองตัวนี้
TRANSPORT_IP_MASTER="${TRANSPORT_IP_MASTER:-$MASTER_IP}"
TRANSPORT_IP_WORKER="${TRANSPORT_IP_WORKER:-$WORKER_IP}"
MASTER_PORT="${MASTER_PORT:-25000}"

# ── NCCL / RoCE (ต้องตั้งชื่อ interface จริงบนเครื่อง; ว่าง = fallback TCP ช้าลง) ──
# หา interface: ip -br link | grep -Ei '200|roce|mlx' ; ibdev2netdev 2>/dev/null
NCCL_SOCKET_IFNAME="${NCCL_SOCKET_IFNAME:-}"
NCCL_IB_HCA="${NCCL_IB_HCA:-}"
NCCL_IB_GID_INDEX="${NCCL_IB_GID_INDEX:-3}"

# ── Paths ──
HF_HOME="${HF_HOME:-${HOME}/.cache/huggingface}"
VLLM_CACHE="${VLLM_CACHE:-${HOME}/.cache/vllm}"
FLASHINFER_CACHE="${FLASHINFER_CACHE:-${HOME}/.cache/flashinfer}"
WORKER_HF_HOME="${WORKER_HF_HOME:-$HF_HOME}"
WORKER_VLLM_CACHE="${WORKER_VLLM_CACHE:-$VLLM_CACHE}"
WORKER_FLASHINFER_CACHE="${WORKER_FLASHINFER_CACHE:-$FLASHINFER_CACHE}"
RUN_DIR="${RUN_DIR:-${HOME}/.lmds/run/deepseek-v4-flash-nvfp4}"
# ล็อก image ต่อ bundle ไม่ใช่ต่อเครื่อง — เครื่องเดียวมี stacked ได้หลายตัวและใช้คนละ image
# (เช่น DeepSeek V4 ต้องใช้ build เฉพาะ ไม่ใช่ image เดียวกับ Llama)
IMAGE_LOCK_FILE="${IMAGE_LOCK_FILE:-${HF_HOME}/.lmds-image-id-deepseek-v4-flash-nvfp4}"

# ── Serving ──
API_HOST="${API_HOST:-0.0.0.0}"
API_PORT="${API_PORT:-8000}"
API_KEY="${API_KEY:-}"
ADVERTISE_IP="${ADVERTISE_IP:-}"
ADVERTISE_INTERFACE="${ADVERTISE_INTERFACE:-}"
ROUTE_PROBE_IP="${ROUTE_PROBE_IP:-1.1.1.1}"

MAX_MODEL_LEN="${MAX_MODEL_LEN:-65536}"
GPU_MEMORY_UTILIZATION="${GPU_MEMORY_UTILIZATION:-0.85}"
MAX_NUM_SEQS="${MAX_NUM_SEQS:-6}"
MAX_NUM_BATCHED_TOKENS="${MAX_NUM_BATCHED_TOKENS:-8192}"
TENSOR_PARALLEL_SIZE="${TENSOR_PARALLEL_SIZE:-2}"
NNODES="${NNODES:-2}"

# feature flags — ว่าง = ปิด (planner เลือกให้แล้ว; override เองได้)
KV_CACHE_DTYPE="${KV_CACHE_DTYPE:-fp8}"
TOOL_CALL_PARSER="${TOOL_CALL_PARSER:-}"
REASONING_PARSER="${REASONING_PARSER:-}"
# MoE backend (เช่น marlin) — ว่างโดยดีฟอลต์ ใส่เองเฉพาะโมเดล MoE ที่ต้องระบุ
MOE_BACKEND="${MOE_BACKEND:-}"
# flag เพิ่มจาก planner (ผ่าน allowlist แล้ว)
EXTRA_SERVE_FLAGS=()

# ── Client budget ──
CLIENT_OUTPUT="${CLIENT_OUTPUT:-8192}"
CLIENT_INPUT="${CLIENT_INPUT:-auto}"
TEMPLATE_OVERHEAD_TOKENS="2048"

# ── Model shard verification (0 = ไม่บังคับจำนวน) ──
SHARD_COUNT="${SHARD_COUNT:-46}"
SHARD_FILES=(
  "model-00001-of-00046.safetensors"
  "model-00002-of-00046.safetensors"
  "model-00003-of-00046.safetensors"
  "model-00004-of-00046.safetensors"
  "model-00005-of-00046.safetensors"
  "model-00006-of-00046.safetensors"
  "model-00007-of-00046.safetensors"
  "model-00008-of-00046.safetensors"
  "model-00009-of-00046.safetensors"
  "model-00010-of-00046.safetensors"
  "model-00011-of-00046.safetensors"
  "model-00012-of-00046.safetensors"
  "model-00013-of-00046.safetensors"
  "model-00014-of-00046.safetensors"
  "model-00015-of-00046.safetensors"
  "model-00016-of-00046.safetensors"
  "model-00017-of-00046.safetensors"
  "model-00018-of-00046.safetensors"
  "model-00019-of-00046.safetensors"
  "model-00020-of-00046.safetensors"
  "model-00021-of-00046.safetensors"
  "model-00022-of-00046.safetensors"
  "model-00023-of-00046.safetensors"
  "model-00024-of-00046.safetensors"
  "model-00025-of-00046.safetensors"
  "model-00026-of-00046.safetensors"
  "model-00027-of-00046.safetensors"
  "model-00028-of-00046.safetensors"
  "model-00029-of-00046.safetensors"
  "model-00030-of-00046.safetensors"
  "model-00031-of-00046.safetensors"
  "model-00032-of-00046.safetensors"
  "model-00033-of-00046.safetensors"
  "model-00034-of-00046.safetensors"
  "model-00035-of-00046.safetensors"
  "model-00036-of-00046.safetensors"
  "model-00037-of-00046.safetensors"
  "model-00038-of-00046.safetensors"
  "model-00039-of-00046.safetensors"
  "model-00040-of-00046.safetensors"
  "model-00041-of-00046.safetensors"
  "model-00042-of-00046.safetensors"
  "model-00043-of-00046.safetensors"
  "model-00044-of-00046.safetensors"
  "model-00045-of-00046.safetensors"
  "model-00046-of-00046.safetensors"
)
SHARD_SIZES=(
  "1059061856"
  "3767827856"
  "3767827856"
  "3797735800"
  "3770275656"
  "3791531376"
  "3770275656"
  "3791531376"
  "3770275656"
  "3791531376"
  "3770275656"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "3770278760"
  "3791534488"
  "1059332508"
  "3593956092"
)
TOTAL_SIZE_APPROX_GB="${TOTAL_SIZE_APPROX_GB:-157}"

STARTUP_TIMEOUT="${STARTUP_TIMEOUT:-5001}"
WORKER_INIT_WAIT="${WORKER_INIT_WAIT:-12}"
# ================================================================================

# ─────────────────────────── helpers ───────────────────────────
die() { echo "ERROR: $*" >&2; exit 1; }
log() { echo "[$(date '+%H:%M:%S')] $*"; }
ssh_at() { local host="$1"; shift; ssh -o BatchMode=yes -o ConnectTimeout=10 "${SSH_USER}@${host}" "$@"; }
# worker ตัวแรก — ใช้กับงานที่อ้างถึง "worker" ตัวเดียวโดยธรรมชาติ
ssh_worker() { ssh_at "$WORKER_IP" "$@"; }
worker_count() { set -- $WORKER_IPS; echo "$#"; }

_require_non_root() {
  if (( EUID == 0 )); then
    die "อย่ารัน controller ด้วย sudo/root — ให้รันเป็น user ปกติที่เป็นเจ้าของ HF cache และตั้ง SSH key ไว้ (sudo เปลี่ยน HOME/SSH_USER ทำให้ image check ชี้ไป root@worker)"
  fi
}

detect_advertise_ip() {
  # คืน 0 เสมอ (พิมพ์ว่างได้ถ้าตรวจไม่เจอ) — กัน set -e ตัดจบเมื่อ bare assignment
  if [[ -n "$ADVERTISE_IP" ]]; then printf '%s' "$ADVERTISE_IP"; return 0; fi
  local found=""
  if [[ -n "$ADVERTISE_INTERFACE" ]]; then
    found="$(ip -4 -o addr show dev "$ADVERTISE_INTERFACE" scope global 2>/dev/null |
      awk 'NR == 1 { split($4, a, "/"); print a[1] }' || true)"
    printf '%s' "$found"; return 0
  fi
  found="$(ip -4 route get "$ROUTE_PROBE_IP" 2>/dev/null |
    awk '{ for (i=1; i<=NF; i++) if ($i=="src") { print $(i+1); exit } }' || true)"
  if [[ -n "$found" ]]; then printf '%s' "$found"; return 0; fi
  found="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
  printf '%s' "$found"
  return 0
}

validate_numbers() {
  [[ "$API_PORT" =~ ^[0-9]+$ ]] && (( API_PORT >= 1 && API_PORT <= 65535 )) ||
    die "invalid API_PORT: $API_PORT"
  [[ "$MAX_MODEL_LEN" =~ ^[0-9]+$ ]] && (( MAX_MODEL_LEN > 0 )) ||
    die "invalid context: $MAX_MODEL_LEN"
  # ต่ำเกิน = ไม่เหลือที่ให้ KV cache · สูงเกิน = ชน OOM ตอน warm-up (unified memory ยิ่งไวเพราะ
  # CPU กับ GPU ใช้ pool เดียวกัน) · bash เทียบทศนิยมไม่ได้ จึงใช้ awk
  awk -v v="$GPU_MEMORY_UTILIZATION" 'BEGIN{exit !(v+0 > 0.3 && v+0 <= 0.98)}' ||
    die "invalid --gpu-util: $GPU_MEMORY_UTILIZATION (ต้องอยู่ระหว่าง 0.3 ถึง 0.98)"
  [[ "$CLIENT_OUTPUT" =~ ^[0-9]+$ ]] && (( CLIENT_OUTPUT > 0 )) ||
    die "invalid CLIENT_OUTPUT: $CLIENT_OUTPUT"
}

parse_options() {
  REMAINING_ARGS=()
  while (( $# )); do
    case "$1" in
      --context)         MAX_MODEL_LEN="$2"; shift 2 ;;
      --context=*)       MAX_MODEL_LEN="${1#*=}"; shift ;;
      --gpu-util)       GPU_MEMORY_UTILIZATION="$2"; shift 2 ;;
      --gpu-util=*)   GPU_MEMORY_UTILIZATION="${1#*=}"; shift ;;
      --port)            API_PORT="$2"; shift 2 ;;
      --port=*)          API_PORT="${1#*=}"; shift ;;
      --bind)            API_HOST="$2"; shift 2 ;;
      --bind=*)          API_HOST="${1#*=}"; shift ;;
      --advertise-ip)    ADVERTISE_IP="$2"; shift 2 ;;
      --advertise-ip=*)  ADVERTISE_IP="${1#*=}"; shift ;;
      --interface)       ADVERTISE_INTERFACE="$2"; shift 2 ;;
      --interface=*)     ADVERTISE_INTERFACE="${1#*=}"; shift ;;
      --client-input)    CLIENT_INPUT="$2"; shift 2 ;;
      --client-input=*)  CLIENT_INPUT="${1#*=}"; shift ;;
      --client-output)   CLIENT_OUTPUT="$2"; shift 2 ;;
      --client-output=*) CLIENT_OUTPUT="${1#*=}"; shift ;;
      *) REMAINING_ARGS+=("$1"); shift ;;
    esac
  done
  validate_numbers
}

# ─────────────────── snapshot path resolution ───────────────────
_model_slug() { printf '%s' "${MODEL_ID//\//--}"; }

_model_cache_dir() {
  local hf_root="${1:-$HF_HOME}" slug candidate
  slug="$(_model_slug)"
  for candidate in "${hf_root}/hub/models--${slug}" "${hf_root}/models--${slug}"; do
    if [[ -d "${candidate}/snapshots" ]]; then printf '%s' "$candidate"; return 0; fi
  done
  printf '%s/hub/models--%s' "$hf_root" "$slug"
}

# path ฝั่งคอนเทนเนอร์ที่ HF ควรใช้เป็น hub cache (mount $HF_HOME ไว้ที่ /cache)
_container_hub_cache() {
  local hf_root="${1:-$HF_HOME}" slug
  slug="$(_model_slug)"
  if [[ -d "${hf_root}/models--${slug}/snapshots" && ! -d "${hf_root}/hub/models--${slug}/snapshots" ]]; then
    printf '/cache'      # เลย์เอาต์เก่า: โมเดลอยู่ที่รากของ HF_HOME
  else
    printf '/cache/hub'
  fi
}

_snapshot_path() {
  local hf_root="${1:-$HF_HOME}" model_dir ref_file commit snap
  model_dir="$(_model_cache_dir "$hf_root")"
  if [[ -d "${model_dir}/snapshots/${MODEL_REVISION}" ]]; then
    printf '%s' "${model_dir}/snapshots/${MODEL_REVISION}"; return 0
  fi
  ref_file="${model_dir}/refs/${MODEL_REVISION}"
  if [[ -f "$ref_file" ]]; then
    commit="$(tr -d '[:space:]' < "$ref_file")"
    if [[ -n "$commit" && -d "${model_dir}/snapshots/${commit}" ]]; then
      printf '%s' "${model_dir}/snapshots/${commit}"; return 0
    fi
  fi
  snap="$(find "${model_dir}/snapshots" -mindepth 1 -maxdepth 1 -type d -print -quit 2>/dev/null || true)"
  if [[ -n "$snap" ]]; then printf '%s' "$snap"; return 0; fi
  printf '%s' "${model_dir}/snapshots/${MODEL_REVISION}"
}

# ─────────────────────── runtime image lock ───────────────────────
_current_image_id() { docker inspect "$VLLM_IMAGE" --format '{{.Id}}' 2>/dev/null || true; }

prepare_runtime() {
  _require_non_root
  need docker
  mkdir -p "$HF_HOME"
  log "Pulling runtime image on head node …"
  docker pull "$VLLM_IMAGE"
  local head_id worker_id
  head_id="$(_current_image_id)"
  [[ -n "$head_id" ]] || die "pull head image ไม่สำเร็จ"
  echo "$head_id" > "$IMAGE_LOCK_FILE"
  log "Head image locked: $head_id"

  local wip
  for wip in $WORKER_IPS; do
    log "Pulling runtime image on worker node (${wip}) …"
    ssh_at "$wip" "docker pull '$VLLM_IMAGE'" || die "pull image บน ${wip} ไม่สำเร็จ (เช็ค SSH/docker)"
  done
  for wip in $WORKER_IPS; do
    worker_id="$(ssh_at "$wip" "docker inspect '$VLLM_IMAGE' --format '{{.Id}}'" || true)"
    [[ -n "$worker_id" ]] || die "อ่าน image id ของ ${wip} ไม่ได้"
    [[ "$head_id" == "$worker_id" ]] ||
      die "image ต่างกันระหว่าง head ($head_id) กับ ${wip} ($worker_id) — re-pull ทุก node"
  done
  log "Runtime images ตรงกันทุก node ($(( $(worker_count) + 1 )) เครื่อง). Lock: ${head_id:0:32}…"
}

_assert_runtime_images() {
  local head_id worker_id locked=""
  head_id="$(_current_image_id)"
  [[ -n "$head_id" ]] || die "ไม่พบ runtime image บน head: ${VLLM_IMAGE} — รัน: $0 prepare-runtime"
  worker_id="$(ssh_worker "docker inspect '$VLLM_IMAGE' --format '{{.Id}}'" 2>/dev/null || true)"
  [[ -n "$worker_id" ]] || die "ไม่พบ runtime image บน worker — รัน: $0 prepare-runtime"
  [[ "$head_id" == "$worker_id" ]] || die "image mismatch head=${head_id} worker=${worker_id} — prepare-runtime ใหม่"
  [[ -f "$IMAGE_LOCK_FILE" ]] && locked="$(cat "$IMAGE_LOCK_FILE")"
  [[ -z "$locked" || "$locked" == "$head_id" ]] ||
    die "image ปัจจุบันต่างจากที่ lock ไว้ — รัน prepare-runtime ใหม่ก่อน start"
  printf '%s' "$head_id"
}

need() { command -v "$1" >/dev/null 2>&1 || die "missing dependency: $1"; }

runtime_info() {
  echo "Image     : $VLLM_IMAGE"
  echo "Backend   : mp (vLLM multiprocessing, TP=${TENSOR_PARALLEL_SIZE}, nnodes=${NNODES})"
  local locked="not yet locked (run prepare-runtime)"
  [[ -f "$IMAGE_LOCK_FILE" ]] && locked="$(cat "$IMAGE_LOCK_FILE")"
  echo "Locked ID : ${locked}"
  docker inspect "$VLLM_IMAGE" --format 'Current ID : {{.Id}}' 2>/dev/null || true
}

# ───────────────────────────── download ─────────────────────────────
download() {
  need docker
  mkdir -p "$HF_HOME"
  log "Downloading ${MODEL_ID} @ ${MODEL_REVISION} (resume-safe) …"
  local dl_args=(
    run --rm -i --network host
    --user "$(id -u):$(id -g)"
    -e HOME=/tmp -e HF_HOME=/cache
    -e "MODEL_ID=${MODEL_ID}" -e "MODEL_REVISION=${MODEL_REVISION}"
    -v "${HF_HOME}:/cache"
  )
  [[ -n "${HF_TOKEN:-}" ]] && dl_args+=(-e "HF_TOKEN=${HF_TOKEN}")
  # Xet เป็น backend ใหม่ของ Hub ที่บาง repo (เช่นตระกูล Llama) ยังพังด้วย
  # "Unable to parse string as hex hash value" — ลองซ้ำโดยปิด Xet ให้อัตโนมัติ
  [[ -n "${HF_HUB_DISABLE_XET:-}" ]] && dl_args+=(-e "HF_HUB_DISABLE_XET=1")
  dl_args+=(--entrypoint python3 "$VLLM_IMAGE" -)

  if ! docker "${dl_args[@]}" <<'PYEOF'
import os
from huggingface_hub import snapshot_download
path = snapshot_download(
    repo_id=os.environ["MODEL_ID"],
    revision=os.environ["MODEL_REVISION"],
    cache_dir="/cache",
)
print("download complete:", path, flush=True)
PYEOF
  then
    [[ -z "${HF_HUB_DISABLE_XET:-}" ]] || die "download ล้มเหลวแม้ปิด Xet แล้ว — ดูข้อความด้านบน"
    log "download ล้มเหลว — ลองใหม่โดยปิด Xet transfer (ไฟล์ที่โหลดแล้วยังอยู่ โหลดต่อจากเดิม)"
    HF_HUB_DISABLE_XET=1 download
    return
  fi
  log "Download complete."
}

# ─────────────────────────── verify-files ───────────────────────────
warn_open_endpoint() {
  # bind 0.0.0.0 + ไม่มี key = ใครก็ตามในวง network ยิง API ได้โดยไม่ต้องยืนยันตัวตน
  [[ "$API_HOST" == "0.0.0.0" && -z "$API_KEY" ]] || return 0
  echo "คำเตือน: เปิดให้ทั้งวง network เข้าถึงได้โดยไม่มี API key" >&2
  echo "         ใช้เฉพาะในเครื่อง: $0 restart --bind 127.0.0.1" >&2
  echo "         หรือบังคับ token:  API_KEY=\$(openssl rand -hex 24) $0 restart" >&2
}

verify_files() {
  local snap; snap="$(_snapshot_path "$HF_HOME")"
  [[ -d "$snap" ]] || die "ยังไม่ได้ download (ไม่พบ $snap) — รัน: $0 download"
  [[ -f "${snap}/config.json" ]] || die "ไฟล์จำเป็นหายไป: config.json"
  local broken
  broken="$(find -L "$snap" -type l 2>/dev/null || true)"
  [[ -z "$broken" ]] || die "พบ symlink เสียใน cache: $broken"
  local n
  n="$(find "$snap" -maxdepth 1 -name '*.safetensors' 2>/dev/null | wc -l | tr -d ' ')"
  (( n >= 1 )) || die "ไม่พบ .safetensors shard ใน ${snap}"
  if (( SHARD_COUNT > 0 )) && (( n != SHARD_COUNT )); then
    die "shard ไม่ครบ: คาด ${SHARD_COUNT} พบ ${n} ใน ${snap}"
  fi

  # ตรวจทีละไฟล์ + ขนาดตรงกับที่ Hub รายงาน — นับจำนวนอย่างเดียวจับไฟล์ที่โหลดไม่ครบไม่ได้
  # สำคัญกว่าฝั่ง single เพราะ stacked มีขั้น rsync ข้ามเครื่องเพิ่มมาอีกจุดที่ไฟล์ขาดได้
  local i path actual_size
  for i in "${!SHARD_FILES[@]}"; do
    path="${snap}/${SHARD_FILES[$i]}"
    [[ -e "$path" ]] || die "shard หายไป: ${SHARD_FILES[$i]} — รัน: $0 download (resume ต่อได้)"
    if [[ -n "${SHARD_SIZES[$i]}" ]]; then
      actual_size="$(stat -Lc %s "$path" 2>/dev/null || stat -Lf %z "$path")"
      [[ "$actual_size" == "${SHARD_SIZES[$i]}" ]] ||
        die "${SHARD_FILES[$i]}: ขนาดไม่ตรง (ได้ ${actual_size} ต้องการ ${SHARD_SIZES[$i]} — download ไม่ครบ?)"
    fi
  done
  echo "shard ครบ ${#SHARD_FILES[@]} ไฟล์ (ขนาดตรงกับ Hub)"

  echo "verify-files: OK (${n} shards @ ${snap})"
}

# ─────────────────────────── sync-worker ───────────────────────────
sync_worker() {
  need rsync
  local snap; snap="$(_snapshot_path "$HF_HOME")"
  [[ -d "$snap" ]] || die "ยังไม่มี snapshot ในเครื่อง — รัน download ก่อน"
  local model_cache cache_name worker_hf
  model_cache="$(_model_cache_dir "$HF_HOME")"
  cache_name="$(basename "$model_cache")"
  worker_hf="${WORKER_HF_HOME}"
  local wip
  for wip in $WORKER_IPS; do
    log "Syncing model cache → worker ${wip} (~${TOTAL_SIZE_APPROX_GB} GB ครั้งแรก)…"
    ssh_at "$wip" "mkdir -p '${worker_hf}/hub' '${WORKER_VLLM_CACHE}' '${WORKER_FLASHINFER_CACHE}'" ||
      die "สร้าง dir บน ${wip} ไม่ได้ (เช็ค SSH)"
    rsync -aH --info=progress2 --no-owner --no-group --partial --append-verify \
      --exclude='*.lock' --exclude='tmp_*' \
      "${model_cache}/" \
      "${SSH_USER}@${wip}:${worker_hf}/hub/${cache_name}/"
  done
  log "sync-worker: DONE"
}

# ─────────────────────────── verify-worker ───────────────────────────
verify_worker() {
  local worker_hf="${WORKER_HF_HOME}" slug wip
  slug="$(_model_slug)"
  for wip in $WORKER_IPS; do
  log "Verifying worker (${wip}) shards …"
  ssh_at "$wip" "docker run --rm -v '${worker_hf}:/cache' -e HF_HOME=/cache -e SHARD_COUNT='${SHARD_COUNT}' -e MODEL_REVISION='${MODEL_REVISION}' -e MODEL_SLUG='${slug}' --entrypoint python3 '$VLLM_IMAGE' - <<'PYEOF'
import os, pathlib, sys
slug = os.environ["MODEL_SLUG"]
rev = os.environ["MODEL_REVISION"]
want = int(os.environ.get("SHARD_COUNT", "0"))
roots = [pathlib.Path("/cache/hub/models--"+slug), pathlib.Path("/cache/models--"+slug)]
model_dir = next((p for p in roots if (p/'snapshots').exists()), roots[0])
snap = model_dir/'snapshots'/rev
ref = model_dir/'refs'/rev
if not snap.exists() and ref.exists():
    snap = model_dir/'snapshots'/ref.read_text().strip()
if not snap.exists():
    snaps = sorted((model_dir/'snapshots').glob('*')) if (model_dir/'snapshots').exists() else []
    if snaps: snap = snaps[-1]
if not snap.exists():
    sys.exit('worker snapshot missing: '+str(snap))
shards = sorted(snap.glob('*.safetensors'))
if not shards:
    sys.exit('no shards on worker')
print('worker shards:', len(shards))
if want and len(shards) != want:
    sys.exit('worker shard count %d != expected %d' % (len(shards), want))
print('verify-worker: PASS')
PYEOF
" || die "verify-worker ล้มเหลวที่ ${wip}"
  done
  log "verify-worker: PASS"
}

# ─────────────────────────── doctor ───────────────────────────
doctor() {
  _require_non_root
  local image_id; image_id="$(_assert_runtime_images)"
  echo "Image: ${VLLM_IMAGE}"
  echo "ID   : ${image_id}"
  docker run --rm --gpus all --entrypoint python3 "$VLLM_IMAGE" - <<'PYEOF'
import platform
try:
    import torch
    print("torch      :", torch.__version__, "| cuda", torch.version.cuda)
    if torch.cuda.is_available():
        print("gpu        :", torch.cuda.get_device_name(0))
        print("capability :", torch.cuda.get_device_capability(0))
except Exception as e:
    print("torch      : unavailable", repr(e))
try:
    import vllm
    print("vllm       :", getattr(vllm, "__version__", "unknown"))
except Exception as e:
    print("vllm       : unavailable", repr(e))
print("python     :", platform.python_version())
PYEOF
}

# ─────────────────────── serve-args builder ───────────────────────
build_common_args() {
  COMMON_ARGS=(
    serve "$MODEL_ID"
    --revision "$MODEL_REVISION"
    --served-model-name "$SERVED_MODEL_NAME"
    --tensor-parallel-size "$TENSOR_PARALLEL_SIZE"
    --distributed-executor-backend mp
    --nnodes "$NNODES"
    --master-addr "$TRANSPORT_IP_MASTER"
    --master-port "$MASTER_PORT"
    --max-model-len "$MAX_MODEL_LEN"
    --max-num-seqs "$MAX_NUM_SEQS"
    --max-num-batched-tokens "$MAX_NUM_BATCHED_TOKENS"
    --gpu-memory-utilization "$GPU_MEMORY_UTILIZATION"
  )
  if [[ -n "$KV_CACHE_DTYPE" && "$KV_CACHE_DTYPE" != "auto" ]]; then
    COMMON_ARGS+=(--kv-cache-dtype "$KV_CACHE_DTYPE")
  fi
  if [[ -n "$MOE_BACKEND" ]]; then
    COMMON_ARGS+=(--moe-backend "$MOE_BACKEND")
  fi
  if [[ -n "$TOOL_CALL_PARSER" ]]; then
    COMMON_ARGS+=(--enable-auto-tool-choice --tool-call-parser "$TOOL_CALL_PARSER")
  fi
  if [[ -n "$REASONING_PARSER" ]]; then
    COMMON_ARGS+=(--reasoning-parser "$REASONING_PARSER")
  fi
  if (( ${#EXTRA_SERVE_FLAGS[@]} > 0 )); then
    COMMON_ARGS+=("${EXTRA_SERVE_FLAGS[@]}")
  fi
}

# หา interface จาก IP ที่ตั้งไว้ — ดีกว่าให้คนกรอกชื่อ interface เอง เพราะชื่อบน DGX Spark
# ยาวและต่างกันระหว่างพอร์ต (enp1s0f1np1 vs enP2p1s0f1np1) พิมพ์ผิดแล้ว NCCL เงียบ ๆ ไปใช้เส้นช้า
detect_interface() {
  local target="$1"
  ip -o -4 addr show 2>/dev/null |
    awk -v want="$target" '$4 ~ ("^" want "/") {print $2; exit}'
}

# interface ของ worker อาจชื่อไม่เหมือน head ต่อให้เป็นเครื่องรุ่นเดียวกัน — ถามเครื่องนั้นเอง
detect_worker_interface() {
  ssh_worker "ip -o -4 addr show 2>/dev/null | awk -v want='${TRANSPORT_IP_WORKER}' \
    '\$4 ~ (\"^\" want \"/\") {print \$2; exit}'" 2>/dev/null || true
}

# RoCE HCA ที่คู่กับ NIC หาได้จาก sysfs — ไม่ตั้งแล้ว NCCL ตกไปใช้ TCP
# สาย 200G จะทำงานได้เท่าอีเทอร์เน็ตธรรมดา ซึ่งเป็นเคสที่ไล่ยากมากเพราะ "ก็รันได้"
detect_hca_for_interface() {
  local want="$1" dev
  [[ -n "$want" ]] || return 0
  for dev in /sys/class/infiniband/*; do
    [[ -e "$dev/device/net/$want" ]] || continue
    basename "$dev"
    return 0
  done
  return 0
}

_resolve_hca() {
  [[ -n "$NCCL_IB_HCA" ]] && return 0
  NCCL_IB_HCA="$(detect_hca_for_interface "$NCCL_SOCKET_IFNAME")"
  [[ -n "$NCCL_IB_HCA" ]] && log "พบ RoCE HCA ของ ${NCCL_SOCKET_IFNAME}: ${NCCL_IB_HCA}"
  return 0
}

_resolve_ifname() {
  # ค่าที่ตั้งมาเองชนะเสมอ ไม่มีค่อยหาให้จาก IP
  [[ -n "$NCCL_SOCKET_IFNAME" ]] && return 0
  NCCL_SOCKET_IFNAME="$(detect_interface "$TRANSPORT_IP_MASTER")"
  [[ -n "$NCCL_SOCKET_IFNAME" ]] &&
    log "พบ interface ของ ${TRANSPORT_IP_MASTER}: ${NCCL_SOCKET_IFNAME}"
  return 0
}

_nccl_env_pairs() {
  # พิมพ์ทีละบรรทัด KEY=VALUE — ใช้ทั้ง head (docker -e) และ worker (export)
  local ifname="${1:-$NCCL_SOCKET_IFNAME}"
  echo "NCCL_IGNORE_CPU_AFFINITY=1"
  echo "NCCL_IB_GID_INDEX=${NCCL_IB_GID_INDEX}"
  if [[ -n "$ifname" ]]; then
    echo "NCCL_SOCKET_IFNAME=${ifname}"
    echo "GLOO_SOCKET_IFNAME=${ifname}"
    echo "TP_SOCKET_IFNAME=${ifname}"
    # UCX/OMPI เลือกเส้นเองแยกจาก NCCL — ไม่บอกด้วยจะหลุดไปใช้ management NIC
    echo "UCX_NET_DEVICES=${ifname}"
    echo "OMPI_MCA_btl_tcp_if_include=${ifname}"
  else
    echo "WARN: หา interface ของ ${TRANSPORT_IP_MASTER} ไม่เจอ — NCCL อาจเลือกเส้นผิด" >&2
  fi
  if [[ -n "$NCCL_IB_HCA" ]]; then
    echo "NCCL_IB_HCA=${NCCL_IB_HCA}"
    echo "NCCL_IB_DISABLE=0"
  else
    echo "NCCL_IB_DISABLE=1"
    echo "WARN: ไม่พบ RoCE HCA ของ ${NCCL_SOCKET_IFNAME:-<ไม่รู้ interface>} — fallback TCP (ช้าลง)" >&2
  fi
}

# ─────────────────────────── start ───────────────────────────
# ถาม IP/user ของคลัสเตอร์ก่อน start — ค่า default ในไฟล์เป็นแค่ตัวอย่าง เครื่องจริงแทบไม่เคยตรง
# (ข้อบังคับของ controller contract v3.0.0 สำหรับ stacked)
# กันเคสรันสคริปต์ head ผิดเครื่อง — เจอตอนเริ่ม ดีกว่าไปตายตอน NCCL init ที่อ่านไม่รู้เรื่อง
check_running_on_master() {
  local ifname
  ifname="$(detect_interface "$TRANSPORT_IP_MASTER")"
  [[ -n "$ifname" ]] || die \
    "เครื่องนี้ไม่มี IP ${TRANSPORT_IP_MASTER} (head) — สคริปต์นี้ต้องรันบนเครื่อง head เท่านั้น
    ถ้าสลับ head/worker ให้แก้ MASTER_IP/WORKER_IP หรือ cluster.env"
}

prompt_cluster_config() {
  [[ -t 0 ]] || return 0
  # ค่ามาจาก hub แล้ว (cluster.env) — ถามซ้ำมีแต่จะให้พิมพ์ผิด
  if [[ -f "$CLUSTER_ENV" ]]; then
    log "ใช้ค่าคลัสเตอร์จาก $CLUSTER_ENV (head ${MASTER_IP} · worker ${WORKER_IP})"
    return 0
  fi
  local ans
  printf '\n== Cluster configuration (กด Enter เพื่อใช้ค่าเดิม) ==\n'
  read -rp "  Head (master) node IP [${MASTER_IP}]: " ans || true; [[ -z "$ans" ]] || MASTER_IP="$ans"
  read -rp "  Worker node IP        [${WORKER_IP}]: " ans || true; [[ -z "$ans" ]] || WORKER_IP="$ans"
  read -rp "  SSH user for nodes    [${SSH_USER}]: " ans || true; [[ -z "$ans" ]] || SSH_USER="$ans"
  TRANSPORT_IP_MASTER="${TRANSPORT_IP_MASTER:-$MASTER_IP}"
  TRANSPORT_IP_WORKER="${TRANSPORT_IP_WORKER:-$WORKER_IP}"
  printf '\n'
}

# ─────────────── ซ่อมสิทธิ์ cache dir ───────────────
# docker เคยสร้าง cache เป็น root มาก่อน → รอบถัดไป user เขียนไม่ได้ แล้ว start ล้มแบบไล่ยาก
# ซ่อมด้วย container ตัวเดิม (ไม่ต้องพึ่ง sudo บน host) — เคสจริงจาก reference v8.2 "permission-safe"
_ensure_local_owned_dir() {
  local dir="$1" uid gid
  uid="$(id -u)"; gid="$(id -g)"
  mkdir -p "$(dirname "$dir")" || die "สร้าง parent ของ $dir ไม่ได้"
  if [[ -e "$dir" && ! -w "$dir" ]]; then
    log "ซ่อมสิทธิ์ cache บน head: $dir"
    docker run --rm -v "$dir:/repair" --entrypoint sh "$VLLM_IMAGE" \
      -c "chown -R ${uid}:${gid} /repair" ||
      die "ซ่อม $dir ไม่ได้ — รันเอง: sudo chown -R ${uid}:${gid} '$dir'"
  fi
  mkdir -p "$dir" || die "สร้าง $dir ไม่ได้"
  [[ -w "$dir" ]] || die "เขียน $dir ไม่ได้ — รันเอง: sudo chown -R ${uid}:${gid} '$dir'"
}

_ensure_worker_owned_dir() {
  local dir="$1" ruid rgid wip
  for wip in $WORKER_IPS; do
    ruid="$(ssh_at "$wip" "id -u")" || die "อ่าน UID ของ ${wip} ผ่าน SSH ไม่ได้"
    rgid="$(ssh_at "$wip" "id -g")" || die "อ่าน GID ของ ${wip} ผ่าน SSH ไม่ได้"
    ssh_at "$wip" "mkdir -p '$(dirname "$dir")'" || die "สร้าง parent บน ${wip} ไม่ได้: $dir"
    if ssh_at "$wip" "test -e '$dir'" 2>/dev/null && ! ssh_at "$wip" "test -w '$dir'" 2>/dev/null; then
      log "ซ่อมสิทธิ์ cache บน ${wip}: $dir"
      ssh_at "$wip" "docker run --rm -v '$dir:/repair' --entrypoint sh '$VLLM_IMAGE' -c 'chown -R ${ruid}:${rgid} /repair'" ||
        die "ซ่อม $dir บน ${wip} ไม่ได้ — บนเครื่องนั้นรัน: sudo chown -R ${ruid}:${rgid} '$dir'"
    fi
    ssh_at "$wip" "mkdir -p '$dir' && test -w '$dir'" || die "เขียน $dir บน ${wip} ไม่ได้"
  done
}

# FlashInfer JIT cache ที่ค้างจาก image เก่าทำให้โหลด TVM-FFI module คนละ signature แล้วพังตอน start
# เป็นทางกู้เดียวเมื่อเจออาการนี้ — ไม่มีคำสั่งนี้ผู้ใช้ติดตาย
# โฟลเดอร์เป็นของ user แต่ไฟล์ข้างในเป็นของ root (คอนเทนเนอร์รอบก่อนสร้างไว้) — เช็ก -w
# ที่ตัวโฟลเดอร์จึงผ่าน แล้วไปตายตอน rm ทีละไฟล์ · chown ทั้งต้นไม้ก่อนเสมอ ไม่ใช่เฉพาะตอนเขียนไม่ได้
_force_own_tree_local() {
  local dir="$1"
  [[ -d "$dir" ]] || return 0
  docker run --rm -v "$dir:/repair" --entrypoint sh "$VLLM_IMAGE" \
    -c "chown -R $(id -u):$(id -g) /repair" >/dev/null 2>&1 || true
}

_force_own_tree_remote() {
  local host="$1" dir="$2" ruid rgid
  ruid="$(ssh_at "$host" "id -u")" || return 0
  rgid="$(ssh_at "$host" "id -g")" || return 0
  ssh_at "$host" "test -d '$dir' && docker run --rm -v '$dir:/repair' --entrypoint sh '$VLLM_IMAGE' \
    -c 'chown -R ${ruid}:${rgid} /repair' >/dev/null 2>&1 || true" || true
}

clear_fi_cache() {
  _require_non_root
  log "หยุด deployment ก่อนล้าง FlashInfer cache …"
  stop
  _ensure_local_owned_dir "$FLASHINFER_CACHE"
  _force_own_tree_local "$FLASHINFER_CACHE"
  log "ล้าง FlashInfer cache บน head: ${FLASHINFER_CACHE}"
  find "$FLASHINFER_CACHE" -mindepth 1 -maxdepth 1 -exec rm -rf -- {} + ||
    die "ล้าง cache บน head ไม่สำเร็จ — ไฟล์อาจเป็นของ root: sudo rm -rf '${FLASHINFER_CACHE}'/*"
  _ensure_worker_owned_dir "$WORKER_FLASHINFER_CACHE"
  local wip
  for wip in $WORKER_IPS; do
    _force_own_tree_remote "$wip" "$WORKER_FLASHINFER_CACHE"
    log "ล้าง FlashInfer cache บน ${wip}: ${WORKER_FLASHINFER_CACHE}"
    ssh_at "$wip" "find '${WORKER_FLASHINFER_CACHE}' -mindepth 1 -maxdepth 1 -exec rm -rf -- {} +" ||
      die "ล้าง cache บน ${wip} ไม่สำเร็จ — ไฟล์อาจเป็นของ root"
  done
  log "ล้างครบทั้งสอง node แล้ว"
}

props() { curl -fsS "http://127.0.0.1:${API_PORT}/v1/models" | python3 -m json.tool; }

start() {
  _require_non_root
  need docker; need curl
  check_running_on_master
  _resolve_ifname
  _resolve_hca
  local WORKER_IFNAME="$NCCL_SOCKET_IFNAME"
  local detected_worker; detected_worker="$(detect_worker_interface)"
  if [[ -n "$detected_worker" ]]; then
    WORKER_IFNAME="$detected_worker"
    [[ "$WORKER_IFNAME" == "$NCCL_SOCKET_IFNAME" ]] ||
      log "worker ใช้ interface คนละชื่อกับ head: ${WORKER_IFNAME}"
  fi
  local image_id; image_id="$(_assert_runtime_images)"
  local cache_key="${image_id#sha256:}"; cache_key="${cache_key:0:16}"
  local head_fi="${FLASHINFER_CACHE}/${cache_key}"
  local worker_fi="${WORKER_FLASHINFER_CACHE}/${cache_key}"

  # port ว่างบน head? — container รันด้วย --network host จึงไม่ "publish" port
  # ตัวกรอง docker publish= จับไม่เจอเลย ต้องดู listening socket จริง
  local listening=""
  if command -v ss >/dev/null 2>&1; then
    listening="$(ss -tln 2>/dev/null || true)"
  elif command -v netstat >/dev/null 2>&1; then
    listening="$(netstat -tln 2>/dev/null || true)"
  fi
  if [[ "$listening" == *":${API_PORT} "* ]]; then
    die "port ${API_PORT} ถูกใช้อยู่บน head — stop ตัวที่ชนก่อน (ดู: ss -tlnp | grep ${API_PORT})"
  fi

  # ลบ container ค้าง
  docker rm -f "$MASTER_CONTAINER" >/dev/null 2>&1 || true
  for wip in $WORKER_IPS; do
    ssh_at "$wip" "docker rm -f '${WORKER_CONTAINER}' >/dev/null 2>&1 || true" || true
  done

  verify_files
  _ensure_local_owned_dir "$FLASHINFER_CACHE"
  _ensure_local_owned_dir "$head_fi"
  _ensure_local_owned_dir "$VLLM_CACHE"
  local worker_hf="${WORKER_HF_HOME}" wip
  for wip in $WORKER_IPS; do
    ssh_at "$wip" "mkdir -p '${worker_hf}' '${WORKER_VLLM_CACHE}'" ||
      die "เตรียม dir บน ${wip} ไม่ได้"
  done
  _ensure_worker_owned_dir "$WORKER_FLASHINFER_CACHE"
  _ensure_worker_owned_dir "$worker_fi"

  build_common_args
  local quoted_common; quoted_common="$(printf ' %q' "${COMMON_ARGS[@]}")"

  # NCCL env สำหรับ docker -e (head) และ export (worker)
  local -a nccl_docker=()
  local line
  while IFS= read -r line; do
    [[ "$line" == WARN:* ]] && continue
    nccl_docker+=(-e "$line")
  done < <(_nccl_env_pairs 2>/dev/null)

  # ── Step 1: worker ทุกตัว (rank 1..N-1, headless) ก่อน ──
  # container ชื่อเดียวกันได้เพราะอยู่คนละเครื่อง · rank เรียงตามลำดับใน WORKER_IPS
  local rank=0 worker_script wifname
  for wip in $WORKER_IPS; do
    rank=$(( rank + 1 ))
    wifname="$(ssh_at "$wip" "ip -o -4 addr show 2>/dev/null | awk -v want='${wip}' \
      '\$4 ~ (\"^\" want \"/\") {print \$2; exit}'" 2>/dev/null || true)"
    [[ -n "$wifname" ]] || wifname="$NCCL_SOCKET_IFNAME"
    log "Starting worker rank ${rank} (headless) on ${wip} [${wifname:-auto}] …"
    worker_script="$(cat <<WSCRIPT
#!/bin/bash
set -e
export VLLM_HOST_IP=${wip}
export HF_HOME=/cache
export HF_HUB_CACHE=$(_container_hub_cache "$WORKER_HF_HOME")
export HF_HUB_OFFLINE=1
export TRANSFORMERS_OFFLINE=1
$(_nccl_env_pairs "$wifname" 2>/dev/null | grep -v '^WARN:' | sed 's/^/export /')
exec vllm${quoted_common} --node-rank ${rank} --host 127.0.0.1 --port 18000 --headless
WSCRIPT
)"
    ssh_at "$wip" "mkdir -p /tmp/lmds-${SLUG} && cat > /tmp/lmds-${SLUG}/worker.sh" <<< "$worker_script"
    ssh_at "$wip" "chmod +x /tmp/lmds-${SLUG}/worker.sh"
    local -a wrun=(
      docker run -d --name "${WORKER_CONTAINER}"
      --gpus all --network host --ipc host
      -v "${worker_hf}:/cache"
      -v "${WORKER_VLLM_CACHE}:/root/.cache/vllm"
      -v "${worker_fi}:/root/.cache/flashinfer"
      -v "/tmp/lmds-${SLUG}:/tmp/lmds-${SLUG}"
      --entrypoint bash "${VLLM_IMAGE}" "/tmp/lmds-${SLUG}/worker.sh"
    )
    ssh_at "$wip" "$(printf '%q ' "${wrun[@]}")" || die "start worker container บน ${wip} ไม่สำเร็จ"
  done

  log "รอ worker init ${WORKER_INIT_WAIT}s …"
  sleep "$WORKER_INIT_WAIT"
  for wip in $WORKER_IPS; do
    if [[ "$(ssh_at "$wip" "docker inspect -f '{{.State.Running}}' '${WORKER_CONTAINER}' 2>/dev/null" || true)" != "true" ]]; then
      ssh_at "$wip" "docker logs --tail 200 '${WORKER_CONTAINER}' 2>&1" || true
      die "worker container บน ${wip} หยุดก่อน head จะเริ่ม — ดู log ด้านบน"
    fi
  done

  # ── Step 2: head (rank 0, serving API) ──
  log "Starting head (rank 0, API) locally …"
  local -a hrun=(
    docker run -d --name "$MASTER_CONTAINER"
    --gpus all --network host --ipc host
    -v "${HF_HOME}:/cache"
    -v "${VLLM_CACHE}:/root/.cache/vllm"
    -v "${head_fi}:/root/.cache/flashinfer"
    -e "VLLM_HOST_IP=${TRANSPORT_IP_MASTER}"
    -e HF_HOME=/cache -e HF_HUB_OFFLINE=1 -e TRANSFORMERS_OFFLINE=1
    -e "HF_HUB_CACHE=$(_container_hub_cache "$HF_HOME")"
  )
  hrun+=("${nccl_docker[@]}")
  [[ -n "$API_KEY" ]] && hrun+=(-e "VLLM_API_KEY=${API_KEY}")
  hrun+=(--entrypoint bash "$VLLM_IMAGE"
    -lc "exec vllm${quoted_common} --node-rank 0 --host $(printf '%q' "$API_HOST") --port $(printf '%q' "$API_PORT")")
  # array ขึ้นต้นด้วย docker อยู่แล้ว — เรียกซ้ำจะได้ `docker docker run -d …`
  "${hrun[@]}"

  write_meta
  # ── Step 3: health poll ──
  log "รอ /health (สูงสุด ${STARTUP_TIMEOUT}s — โหลดโมเดลใหญ่ + warm-up ข้าม node ใช้เวลานาน)…"
  local deadline=$(( $(date +%s) + STARTUP_TIMEOUT ))
  while (( $(date +%s) < deadline )); do
    if curl -fsS "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; then
      log "Server พร้อม"
      echo "started: $(detect_advertise_ip):${API_PORT} (${SERVED_MODEL_NAME})"
      warn_open_endpoint
      network_info
      return 0
    fi
    if [[ "$(docker inspect -f '{{.State.Running}}' "$MASTER_CONTAINER" 2>/dev/null || true)" != "true" ]]; then
      die "head container หยุดก่อน health ผ่าน — ดู: $0 logs head 200"
    fi
    sleep 10
  done
  die "ไม่ health ภายใน ${STARTUP_TIMEOUT}s — container ยังรันอยู่ ดู: $0 logs head 200"
}

write_meta() {
  mkdir -p "$RUN_DIR"
  local script_path
  script_path="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/$(basename "${BASH_SOURCE[0]}")"
  cat > "${RUN_DIR}/server.meta" <<EOF
slug=${SLUG}
model=${SERVED_MODEL_NAME}
model_id=${MODEL_ID}
engine=vllm
mode=docker
port=${API_PORT}
container=${MASTER_CONTAINER}
pid_file=
controller=${script_path}
started_at=$(date +%Y-%m-%dT%H:%M:%S)
EOF
}

# ─────────────────────────── stop ───────────────────────────
stop() {
  log "Stopping head …"
  docker rm -f "$MASTER_CONTAINER" >/dev/null 2>&1 || true
  log "Stopping worker on ${WORKER_IP} …"
  local wip
  for wip in $WORKER_IPS; do
    ssh_at "$wip" "docker rm -f '${WORKER_CONTAINER}' >/dev/null 2>&1 || true" || true
  done
  # mp backend ทิ้ง shared memory ไว้ — ไม่เก็บกวาด start รอบหน้าจะชนของเก่า
  sudo -n sh -c 'rm -f /dev/shm/psm_* /dev/shm/sem.mp-*' 2>/dev/null || true
  for wip in $WORKER_IPS; do
    ssh_at "$wip" "sudo -n sh -c 'rm -f /dev/shm/psm_* /dev/shm/sem.mp-*' 2>/dev/null || true" || true
  done
  echo "stopped ${MASTER_CONTAINER} + ${WORKER_CONTAINER}"
}

# ─────────────────────────── status ───────────────────────────
status() {
  echo "Model   : ${SERVED_MODEL_NAME} (${MODEL_ID})"
  echo "Topology: stacked TP=${TENSOR_PARALLEL_SIZE} nnodes=${NNODES}  head=${MASTER_IP} worker=${WORKER_IP}"
  echo "--- Head (local) ---"
  docker ps -a --filter "name=^${MASTER_CONTAINER}$" --format 'table {{.Names}}\t{{.Status}}' 2>/dev/null || true
  echo "--- Worker (${WORKER_IP}) ---"
  local wip
  for wip in $WORKER_IPS; do
    echo "-- worker ${wip}"
    ssh_at "$wip" "docker ps -a --filter 'name=^${WORKER_CONTAINER}$' --format 'table {{.Names}}\t{{.Status}}'" 2>/dev/null || echo "(SSH ล้มเหลว)"
  done
  echo "--- API ---"
  if curl -fsS "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; then
    echo "API: healthy"
    curl -fsS ${API_KEY:+-H "Authorization: Bearer $API_KEY"} \
      "http://127.0.0.1:${API_PORT}/v1/models" 2>/dev/null || true
    echo ""
  else
    echo "API: not responding (http://127.0.0.1:${API_PORT})"
  fi
}

# ─────────────────────────── logs ───────────────────────────
logs() {
  # รองรับทั้ง `logs <N>` (fleet: head N บรรทัด) และ `logs <head|worker> [N]`
  local target n
  if [[ "${1:-}" =~ ^[0-9]+$ ]]; then
    target="head"; n="${1}"
  else
    target="${1:-head}"; n="${2:-200}"
  fi
  case "$target" in
    head|master) docker logs --tail "$n" "$MASTER_CONTAINER" 2>&1 ;;
    worker)      for wip in $WORKER_IPS; do
                   echo "===== worker ${wip} ====="
                   ssh_at "$wip" "docker logs --tail '$n' '${WORKER_CONTAINER}' 2>&1" || true
                 done ;;
    *)           die "logs target ต้องเป็น: head | worker (หรือใส่ตัวเลขจำนวนบรรทัด)" ;;
  esac
}

# ─────────────────────────── network-info ───────────────────────────
network_info() {
  local adv; adv="$(detect_advertise_ip)"
  echo "Head IP    : ${MASTER_IP}  (transport ${TRANSPORT_IP_MASTER})"
  echo "Worker IP  : ${WORKER_IP}  (transport ${TRANSPORT_IP_WORKER})"
  echo "NCCL if    : ${NCCL_SOCKET_IFNAME:-<ยังไม่ตั้ง — แนะนำให้ตั้ง>}"
  echo "NCCL HCA   : ${NCCL_IB_HCA:-<ยังไม่ตั้ง — จะ fallback TCP>}"
  echo "Master port: ${MASTER_PORT}"
  echo "Bind       : ${API_HOST}:${API_PORT}"
  echo "Endpoint   : http://${adv}:${API_PORT}/v1"
  echo "Model      : ${SERVED_MODEL_NAME}"
  echo "Context    : ${MAX_MODEL_LEN}"
  echo "Discover fabric: ip -br link | grep -Ei '200|roce|mlx'"
}

# ─────────────────────────── client-config ───────────────────────────
client_config() {
  local input_budget
  if [[ "$CLIENT_INPUT" == "auto" ]]; then
    input_budget=$(( MAX_MODEL_LEN - CLIENT_OUTPUT - TEMPLATE_OVERHEAD_TOKENS ))
  else
    input_budget="$CLIENT_INPUT"
  fi
  (( input_budget > 0 )) || die "context เล็กเกิน: input budget = ${input_budget}"
  cat <<EOF
{
  "base_url": "http://$(detect_advertise_ip):${API_PORT}/v1",
  "model": "${SERVED_MODEL_NAME}",
  "api_key": "${API_KEY:-not-required}",
  "max_input_tokens": ${input_budget},
  "max_output_tokens": ${CLIENT_OUTPUT},
  "server_context": ${MAX_MODEL_LEN}
}
EOF
}

# ─────────────────────────── test-text ───────────────────────────
test_text() {
  # 512 ไม่ใช่ 64: โมเดลสาย reasoning ใช้ budget ไปกับ <think> ก่อน ถ้าให้น้อยจะได้
  # finish_reason "length" โดยยังไม่ทันตอบ ซึ่งดูเหมือนโมเดลพัง
  local response
  response="$(curl -fsS "http://127.0.0.1:${API_PORT}/v1/chat/completions" \
    ${API_KEY:+-H "Authorization: Bearer $API_KEY"} \
    -H "Content-Type: application/json" \
    -d "{
      \"model\": \"${SERVED_MODEL_NAME}\",
      \"messages\": [{\"role\": \"user\", \"content\": \"ตอบสั้น ๆ: 2+2 เท่ากับเท่าไร\"}],
      \"max_tokens\": 512
    }")" || die "เรียก /v1/chat/completions ไม่สำเร็จ — ดู log: $0 logs 200"

  echo "$response"
  echo ""

  if command -v python3 >/dev/null 2>&1; then
    printf "%s" "$response" | python3 -c '
import json, re, sys
try:
    msg = json.load(sys.stdin)["choices"][0]["message"]
except (ValueError, KeyError, IndexError):
    sys.exit(0)
raw = msg.get("content") or ""
answer = re.sub(r"(?s)^.*?</think>", "", raw).strip()
if answer:
    print("test-text: OK — " + answer[:200])
elif raw.strip() or (msg.get("reasoning_content") or "").strip():
    print("test-text: โมเดลตอบแต่ยังคิดไม่จบใน 512 tokens (reasoning model)")
    print("           ไม่ใช่ความผิดพลาด — เซิร์ฟเวอร์รับงานและตอบกลับได้ปกติ")
else:
    print("test-text: เซิร์ฟเวอร์ตอบกลับแต่ไม่มีข้อความ — ดู log: logs 200")
' || true
  fi
}

usage() {
  cat <<EOF
{{ slug }} — vLLM stacked (multi-node) controller  (model: ${MODEL_ID})

USAGE
  $0 <command> [options]

Run every command from the MASTER node as a normal user (never sudo).
Before the first start you MUST set MASTER_IP / WORKER_IP / SSH_USER /
NCCL_SOCKET_IFNAME / NCCL_IB_HCA in the CONFIG block at the top of this file,
and set up passwordless SSH from master to worker.

COMMANDS (Thai descriptions kept — same wording as the run output):
  prepare-runtime  pull + lock image ให้ตรงกันทั้งสอง node
  runtime-info     แสดง image / lock id
  download         ดาวน์โหลดโมเดลลง head (resume ได้, pin revision)
  verify-files     ตรวจ config + จำนวน shard + symlink บน head
  sync-worker      rsync model cache → worker
  verify-worker    ตรวจ shard บน worker
  doctor           ตรวจ image/GPU/vLLM ให้ตรงกัน
  start            worker-first → head → รอ /health
  stop | restart   หยุด / restart ทั้งสอง node
  status           สถานะ container ทั้งสอง node + API
  logs [head|worker] [N]   log (หรือ logs N = head N บรรทัด)
  client-config    ค่าตั้ง client (JSON) พร้อม token budget
  network-info     IP/fabric/endpoint
  props            รายการโมเดลจาก /v1/models
  clear-fi-cache   หยุดแล้วล้าง FlashInfer JIT cache ทั้งสอง node
                   ใช้เมื่อ start พังหลังเปลี่ยน image (cache เก่าคนละ signature)
  test-text        ทดสอบ chat completion

OPTIONS  (can be placed after any command; equals form also works: --port=8001)
  --port N              Port the head node serves on             [default: ${API_PORT}]
  --context N           Max context length in tokens             [default: ${MAX_MODEL_LEN}]
  --bind ADDR           Address the head node listens on         [default: ${API_HOST}]
                        0.0.0.0 = whole network · 127.0.0.1 = this machine only
  --advertise-ip ADDR   IP printed for clients (does NOT change the bind address)
  --interface NAME      Pick the advertised IP from this interface instead of auto-detect
  --client-input N|auto Input token budget written into client-config
  --client-output N     Output token budget written into client-config

API TOKEN (authentication)
  There is NO token by default: anyone who can reach ${API_HOST}:${API_PORT} can use the model.
  Set one with the API_KEY environment variable — it is passed to vLLM as VLLM_API_KEY on the head node:

    API_KEY=my-secret-token $0 restart          # restart both nodes with authentication on
    API_KEY=\$(openssl rand -hex 24) $0 restart  # or generate a random one

  Clients then send it as a bearer token:

    curl http://<master-ip>:${API_PORT}/v1/chat/completions \
      -H "Authorization: Bearer my-secret-token" \
      -H 'Content-Type: application/json' \
      -d '{"model":"${SERVED_MODEL_NAME}","messages":[{"role":"user","content":"hi"}]}'

  The token is NOT stored in this script — pass API_KEY on every start/restart.
  Only the head node serves the API; the worker never exposes one.
  Without a token, prefer:  $0 restart --bind 127.0.0.1

ENVIRONMENT VARIABLES
  API_KEY               Bearer token required from clients        [default: none]
  API_PORT / API_HOST   Same as --port / --bind
  MAX_MODEL_LEN         Same as --context
  HF_TOKEN              Hugging Face token, needed for gated repos during 'download'
  HF_HOME               Where model weights live on BOTH nodes    [default: \${HOME}/.cache/huggingface]
  SHARD_COUNT           Expected shard count (0 = do not enforce) [default: ${SHARD_COUNT}]
  STARTUP_TIMEOUT       Seconds to wait for /health on start      [default: ${STARTUP_TIMEOUT}]

EXAMPLES
  $0 prepare-runtime && $0 download && $0 verify-files    # first run, on master
  $0 sync-worker && $0 verify-worker                      # copy weights to the worker and check
  $0 start                                                # worker first, then head
  API_KEY=secret123 $0 restart                            # require a bearer token
  $0 logs worker 200                                      # worker-side logs
  $0 doctor                                               # image / GPU / vLLM consistency across nodes
EOF
}

parse_options "$@"
set -- ${REMAINING_ARGS[@]+"${REMAINING_ARGS[@]}"}


banner() {
  cat <<'ART'

  _     __  __ ____  ____
 | |   |  \/  |  _ \/ ___|
 | |   | |\/| | | | \___ \
 | |___| |  | | |_| |___) |
 |_____|_|  |_|____/|____/
ART
  printf '       =[ LMDS controller · v%s ]\n' "${SCRIPT_VERSION}"
  printf '+ -- --=[ %s ]\n' "${MODEL_LABEL}"
  printf '+ -- --=[ %s · %s ]\n' "${RUNTIME_LABEL}" "${MODEL_FEATURES}"
  printf '+ -- --=[ Designed by neronain · fb.com/neronain.minidev ]\n\n'
}

# สรุปว่า controller นี้เสิร์ฟโมเดลอะไร ที่พอร์ตไหน และตอนนี้ขึ้นหรือยัง
info() {
  banner
  local ip url state
  ip="$(detect_advertise_ip 2>/dev/null || true)"; [[ -n "$ip" ]] || ip="${API_HOST}"
  url="http://${ip}:${API_PORT}/v1"
  state="stopped"
  if curl -fsS -m 2 "http://127.0.0.1:${API_PORT}/health" >/dev/null 2>&1; then
    state="RUNNING"
  fi
  printf '  Model     : %s\n'            "${MODEL_LABEL}"
  printf '  Model ID  : %s\n'            "${MODEL_ID}"
  printf '  Runtime   : %s\n'            "${RUNTIME_LABEL}"
  printf '  Features  : %s\n'            "${MODEL_FEATURES}"
  printf '  Context   : %s tokens\n'     "${MAX_MODEL_LEN:-${CTX_SIZE:-n/a}}"
  printf '  API (v1)  : %s\n'            "${url}"
  printf '  State     : %s  (port %s)\n\n' "${state}" "${API_PORT}"
}

case "${1:-}" in start|restart) prompt_cluster_config ;; esac

case "${1:-help}" in
  prepare-runtime) prepare_runtime ;;
  runtime-info)    runtime_info ;;
  download)        download ;;
  verify-files)    verify_files ;;
  sync-worker)     sync_worker ;;
  verify-worker)   verify_worker ;;
  doctor)          doctor ;;
  start)           start ;;
  stop)            stop ;;
  restart)         stop; start ;;
  status)          status ;;
  logs)            logs "${2:-head}" "${3:-200}" ;;
  client-config)   client_config ;;
  clear-fi-cache)  clear_fi_cache ;;
  props)           props ;;
  info|banner) info ;;
  network-info)    network_info ;;
  test-text)       test_text ;;
  *)               usage ;;
esac

